"""TradingView MCP client, exercised end to end against a local OAuth-protected server.

TradingView's real server is unreachable from CI and needs a paid account, so
this builds the closest faithful stand-in: a real streamable-HTTP MCP server
behind a minimal OAuth 2.1 authorization server (protected-resource metadata,
AS metadata, dynamic client registration, authorize redirect, token endpoint).
Everything on the client side is the production code path.
"""
from __future__ import annotations

import asyncio
import json
import os
import socket
import threading
import time
import urllib.request
from urllib.parse import parse_qs, urlencode, urlparse

import pytest

from tascreen.errors import ProviderError
from tascreen.tv.mcp_client import (
    AuthorizationRequired,
    FileTokenStorage,
    LocalCallback,
    TradingViewMCP,
    describe_result,
    describe_tools,
    is_read_only,
    parse_tool_args,
)


def _free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _fake_tradingview_mcp():
    from mcp.server import MCPServer

    srv = MCPServer("fake-tradingview")

    @srv.tool()
    def get_quote(symbol: str) -> dict:
        """Latest quote for an EXCHANGE:TICKER symbol."""
        return {"symbol": symbol, "close": 101.25, "market_cap": 2.5e12}

    return srv


# ------------------------------------------------------------ local OAuth server
class FakeAuthServer:
    """Serves MCP at /mcp only to callers holding the token it issued."""

    TOKEN = "access-token-1"

    def __init__(self, dcr: bool = True, waf: bool = False, expires_in: int = 3600):
        self.expires_in = expires_in          # lifetime of every access token issued
        self.dcr = dcr                       # False: no registration endpoint at all
        self.waf = waf                       # True: 403 for requests without a known User-Agent
        self.user_agents: list[str] = []
        self.port = _free_port()
        self.base = f"http://127.0.0.1:{self.port}"
        self.registrations: list[dict] = []
        self.token_requests: list[dict] = []
        self.valid_token = self.TOKEN          # the only access token /mcp accepts
        self.refresh_ok = True
        self._mcp_app = _fake_tradingview_mcp().streamable_http_app()
        self._server = None

    async def app(self, scope, receive, send):
        from starlette.requests import Request
        from starlette.responses import JSONResponse, Response

        if scope["type"] != "http":
            return await self._mcp_app(scope, receive, send)   # lifespan etc.

        path, base = scope["path"], self.base
        request = Request(scope, receive)
        agent = request.headers.get("user-agent", "")
        self.user_agents.append((path, agent))
        if self.waf and path != "/authorize" and not agent.startswith("ta-screener"):
            # like TradingView's bot protection on its API endpoints: the SDK's bare
            # requests get 403. /authorize is loaded by the user's real browser, so
            # only its own rule (below) applies there.
            return await Response(status_code=403)(scope, receive, send)

        if path.startswith("/.well-known/oauth-protected-resource"):
            resp = JSONResponse({"resource": f"{base}/mcp", "authorization_servers": [base]})
        elif path.startswith("/.well-known/oauth-authorization-server"):
            meta = {
                "issuer": base,
                "authorization_endpoint": f"{base}/authorize",
                # Not at /token: TradingView's is /mcp/oauth/token on another host, and
                # the SDK's refresh-before-discovery guessed <mcp host>/token (live 404).
                "token_endpoint": f"{base}/oauth/token",
                "response_types_supported": ["code"],
                "grant_types_supported": ["authorization_code", "refresh_token"],
                "code_challenge_methods_supported": ["S256"],
                "token_endpoint_auth_methods_supported": ["none"],
            }
            if self.dcr:
                meta["registration_endpoint"] = f"{base}/register"
            resp = JSONResponse(meta)
        elif path == "/authorize":
            q = request.query_params
            if self.waf and "127.0.0.1" in q.get("redirect_uri", ""):
                # what the live browser showed: CloudFront blocks an IP-literal redirect
                resp = Response("<h1>403 ERROR</h1>The request could not be satisfied. "
                                "Generated by cloudfront (CloudFront)", status_code=403,
                                headers={"x-amz-cf-id": "fake-cf-id",
                                         "X-Cache": "Error from cloudfront"})
            elif q.get("client_id") == "diagnostic-probe":
                # the origin's own error for an unknown client, relayed by the CDN —
                # carries x-amz-cf-id like every CloudFront response, but is not a block
                resp = JSONResponse({"error": "invalid_client"}, status_code=400,
                                    headers={"x-amz-cf-id": "fake-cf-id", "X-Cache": "Miss from cloudfront"})
            else:
                target = f"{q['redirect_uri']}?{urlencode({'code': 'auth-code-xyz', 'state': q.get('state', '')})}"
                resp = Response(status_code=302, headers={"Location": target})
        elif path == "/register" and self.dcr:
            body = await request.json()
            self.registrations.append(body)
            resp = JSONResponse({**body, "client_id": "client-123"}, status_code=201)
        elif path == "/oauth/token":
            form = dict(await request.form())
            self.token_requests.append(form)
            if form.get("grant_type") == "refresh_token":
                if not self.refresh_ok or form.get("refresh_token") != "refresh-1":
                    resp = JSONResponse({"error": "invalid_grant"}, status_code=400)
                    return await resp(scope, receive, send)
                self.valid_token = f"access-token-{len(self.token_requests)}"
            else:
                self.valid_token = self.TOKEN
            resp = JSONResponse({"access_token": self.valid_token, "token_type": "Bearer",
                                 "expires_in": self.expires_in, "refresh_token": "refresh-1"})
        elif path.startswith("/mcp"):
            auth = dict(scope["headers"]).get(b"authorization", b"").decode()
            if auth != f"Bearer {self.valid_token}":
                resp = Response(status_code=401, headers={
                    "WWW-Authenticate":
                        f'Bearer resource_metadata="{base}/.well-known/oauth-protected-resource"'})
            else:
                return await self._mcp_app(scope, receive, send)
        else:
            resp = Response(status_code=404)
        await resp(scope, receive, send)

    def start(self):
        import uvicorn

        self._server = uvicorn.Server(uvicorn.Config(self.app, host="127.0.0.1", port=self.port,
                                                     log_level="warning", lifespan="on",
                                                     interface="asgi3"))
        threading.Thread(target=self._server.run, daemon=True).start()
        deadline = time.time() + 10
        while not self._server.started:
            if time.time() > deadline:
                raise RuntimeError("fake server did not start")
            time.sleep(0.05)

    def stop(self):
        self._server.should_exit = True


@pytest.fixture
def auth_server():
    server = FakeAuthServer()
    server.start()
    yield server
    server.stop()


def _browser_that_approves(auth_url: str) -> None:
    """Plays the user's browser: loads the authorize URL, which redirects back to
    the local callback with a code. A CDN block stops it there, as it did live."""
    def load():
        time.sleep(0.2)
        try:
            urllib.request.urlopen(auth_url)          # follows the 302 to the callback
        except Exception:  # noqa: BLE001 — a blocked page just never calls back
            pass

    threading.Thread(target=load, daemon=True).start()


def _client(server, tmp_path, *, interactive, browser=_browser_that_approves, port=None,
            host="localhost", timeout=20):
    return TradingViewMCP(url=f"{server.base}/mcp", token_path=tmp_path / "tv_tokens.json",
                          callback_host=host, callback_port=port or _free_port(),
                          interactive=interactive, open_browser=browser, sign_in_timeout=timeout)


# ------------------------------------------------------------------ OAuth flow
def test_headless_run_without_tokens_asks_for_sign_in_instead_of_hanging(auth_server, tmp_path):
    started = time.time()
    with pytest.raises(AuthorizationRequired, match="--auth-tradingview"):
        _client(auth_server, tmp_path, interactive=False).list_tools()
    assert time.time() - started < 15


def test_sign_in_stores_tokens_and_headless_runs_reuse_them(auth_server, tmp_path):
    tools = _client(auth_server, tmp_path, interactive=True).list_tools()
    assert [t.name for t in tools] == ["get_quote"]

    # dynamic registration used our loopback redirect and asked for refresh tokens
    reg = auth_server.registrations[0]
    assert reg["redirect_uris"][0].startswith("http://localhost:")
    assert "refresh_token" in reg["grant_types"]
    # the code was exchanged with PKCE
    assert auth_server.token_requests[0]["code"] == "auth-code-xyz"
    assert auth_server.token_requests[0]["code_verifier"]

    stored = json.loads((tmp_path / "tv_tokens.json").read_text())
    assert stored["tokens"]["access_token"] == FakeAuthServer.TOKEN
    assert stored["client_info"]["client_id"] == "client-123"

    def no_browser(url):
        raise AssertionError("a headless run must not open a browser")

    headless = _client(auth_server, tmp_path, interactive=False, browser=no_browser)
    result = headless.call_tool("get_quote", {"symbol": "NASDAQ:NVDA"})
    assert not result.is_error
    assert json.loads(result.content[0].text)["close"] == 101.25
    assert len(auth_server.token_requests) == 1          # no second sign-in


def test_unreachable_server_is_a_provider_error_not_a_crash(tmp_path):
    client = TradingViewMCP(url=f"http://127.0.0.1:{_free_port()}/mcp",
                            token_path=tmp_path / "t.json", interactive=False)
    with pytest.raises(ProviderError) as info:
        client.list_tools()
    # a construction bug (bad kwargs) would also end up here — make sure it is not one
    assert "TypeError" not in str(info.value) and "ValidationError" not in str(info.value)


# ------------------------------------------------------------------ components
def test_token_storage_round_trip(tmp_path):
    from mcp.shared.auth import OAuthToken

    storage = FileTokenStorage(tmp_path / "nested" / "tokens.json")
    assert asyncio.run(storage.get_tokens()) is None
    asyncio.run(storage.set_tokens(OAuthToken(access_token="a", refresh_token="r", expires_in=60)))
    again = asyncio.run(FileTokenStorage(tmp_path / "nested" / "tokens.json").get_tokens())
    assert again.access_token == "a" and again.refresh_token == "r"


def test_callback_reports_a_denied_sign_in(tmp_path):
    cb = LocalCallback("127.0.0.1", _free_port())
    cb.start()
    try:
        threading.Thread(target=lambda: _get_ignoring_errors(
            f"{cb.redirect_uri}?error=access_denied"), daemon=True).start()
        with pytest.raises(AuthorizationRequired, match="access_denied"):
            asyncio.run(cb.wait(timeout=5))
    finally:
        cb.stop()


def _get_ignoring_errors(url):
    time.sleep(0.1)
    try:
        urllib.request.urlopen(url)
    except Exception:  # noqa: BLE001 — 400 response is expected
        pass


def test_in_process_server_listing_and_call_are_readable():
    client = TradingViewMCP(server=_fake_tradingview_mcp())
    listing = describe_tools(client.list_tools())
    assert "get_quote" in listing and "symbol: string (required)" in listing
    text = describe_result(client.call_tool("get_quote", {"symbol": "NASDAQ:NVDA"}))
    assert "is_error: False" in text and "101.25" in text


def test_parse_tool_args_handles_json_and_strings():
    assert parse_tool_args(["symbol=NASDAQ:NVDA", "limit=5", "adjusted=true"]) == {
        "symbol": "NASDAQ:NVDA", "limit": 5, "adjusted": True}
    with pytest.raises(ValueError):
        parse_tool_args(["oops"])


def test_parse_tool_args_accepts_lists_after_powershell_strips_quotes():
    # PowerShell turns symbols=["NASDAQ:NVDA","NASDAQ:AMD"] into symbols=[NASDAQ:NVDA,NASDAQ:AMD]
    assert parse_tool_args(["symbols=[NASDAQ:NVDA, NASDAQ:AMD]"]) == {
        "symbols": ["NASDAQ:NVDA", "NASDAQ:AMD"]}
    assert parse_tool_args(['symbols=["NASDAQ:NVDA"]']) == {"symbols": ["NASDAQ:NVDA"]}


@pytest.mark.parametrize("name,allowed", [
    ("mcp-tv-get-ohlcv", True),
    ("mcp-tv-get-earnings-calendar", True),
    ("mcp-tv-list-alerts", True),
    ("mcp-tv-search-symbols", True),
    ("mcp-tv-run-screener", True),
    ("mcp-watchlist-get-watchlist", True),
    ("get_quote", True),
    ("mcp-tv-create-alert", False),
    ("mcp-tv-delete-alert", False),
    ("mcp-tv-update-alert", False),
    ("mcp-tv-restart-alerts", False),
    ("mcp-tv-stop-alerts", False),
    ("mcp-watchlist-add-to-watchlist", False),
    ("mcp-watchlist-delete-watchlist", False),
    ("mcp-watchlist-remove-from-watchlist", False),
])
def test_only_read_only_tools_are_callable(name, allowed):
    assert is_read_only(name) is allowed


def test_write_tool_is_refused_before_any_request():
    client = TradingViewMCP(server=_fake_tradingview_mcp())
    with pytest.raises(ProviderError, match="refusing to call"):
        client.call_tool("mcp-tv-create-alert", {"symbol": "NASDAQ:NVDA", "price": 1})


# ----------------------------------------------------------------- diagnostics
def test_diagnose_reports_the_sign_in_routes(auth_server):
    from tascreen.tv.mcp_client import diagnose

    text = "\n".join(diagnose(f"{auth_server.base}/mcp"))
    assert "authorization_servers" in text
    assert f"dynamic client registration : yes -> {auth_server.base}/register" in text
    assert "client ID metadata document : NO" in text


def test_server_without_registration_gets_an_actionable_error(tmp_path):
    """What the first live sign-in hit: TradingView answered /register with 404."""
    from tascreen.tv.mcp_client import diagnose

    server = FakeAuthServer(dcr=False)
    server.start()
    try:
        assert "dynamic client registration : NO" in "\n".join(diagnose(f"{server.base}/mcp"))
        with pytest.raises(ProviderError, match="--tradingview-diagnose"):
            _client(server, tmp_path, interactive=True).list_tools()
    finally:
        server.stop()


# ------------------------------------------------------------- bot protection
def test_sdk_bare_request_is_blocked_but_ours_passes():
    """Reproduces the live finding: 403 for the SDK's discovery request, 200 for ours."""
    from tascreen.tv.mcp_client import _compare_headers

    server = FakeAuthServer(waf=True)
    server.start()
    try:
        lines = _compare_headers(f"{server.base}/.well-known/oauth-authorization-server")
        assert "403" in lines[0] and "as the SDK sends it" in lines[0]
        assert "200" in lines[1] and "with our headers" in lines[1]
    finally:
        server.stop()


def test_sign_in_succeeds_behind_bot_protection(tmp_path):
    server = FakeAuthServer(waf=True)
    server.start()
    try:
        tools = _client(server, tmp_path, interactive=True).list_tools()
        assert [t.name for t in tools] == ["get_quote"]
        assert server.registrations, "registration must reach the real endpoint"
        # every request our client sent identified itself (the browser loads /authorize)
        ours = [agent for path, agent in server.user_agents if path != "/authorize"]
        assert ours and all(a.startswith("ta-screener") for a in ours)
    finally:
        server.stop()


# ------------------------------------------------------------------ CDN block
def test_ip_literal_redirect_is_blocked_by_the_cdn_like_live(tmp_path):
    """Reproduces the live symptom: with 127.0.0.1 in the redirect, the sign-in
    page is a CloudFront 403 and no code ever comes back."""
    server = FakeAuthServer(waf=True)
    server.start()
    try:
        with pytest.raises(AuthorizationRequired, match="no sign-in completed"):
            _client(server, tmp_path, interactive=True, host="127.0.0.1", timeout=3).list_tools()
    finally:
        server.stop()


def test_diagnose_shows_which_redirect_host_the_cdn_blocks():
    from tascreen.tv.mcp_client import diagnose

    server = FakeAuthServer(waf=True)
    server.start()
    try:
        text = "\n".join(diagnose(f"{server.base}/mcp"))
        assert "127.0.0.1  -> 403  BLOCKED by CDN" in text
        assert "localhost  -> 400  reached the sign-in server" in text
        assert "invalid_client" in text            # the page says who answered
    finally:
        server.stop()


def test_client_registered_with_old_redirect_is_re_registered(auth_server, tmp_path):
    """The live run registered a client with 127.0.0.1 before the page was blocked;
    that stored client must be replaced, not reused with a mismatched redirect."""
    _client(auth_server, tmp_path, interactive=True, host="127.0.0.1").list_tools()
    assert len(auth_server.registrations) == 1

    _client(auth_server, tmp_path, interactive=True, host="localhost").list_tools()
    assert len(auth_server.registrations) == 2
    assert auth_server.registrations[1]["redirect_uris"][0].startswith("http://localhost:")
    stored = json.loads((tmp_path / "tv_tokens.json").read_text())
    assert stored["client_info"]["redirect_uris"][0].startswith("http://localhost:")


@pytest.mark.parametrize("address", ["127.0.0.1", "[::1]"])
def test_localhost_callback_answers_on_ipv4_and_ipv6(address):
    port = _free_port()
    cb = LocalCallback("localhost", port)
    cb.start()
    try:
        if address == "[::1]" and len(cb._servers) < 2:
            pytest.skip("no IPv6 loopback on this machine")
        threading.Thread(target=lambda: _get_ignoring_errors(
            f"http://{address}:{port}/callback?code=c1&state=s1"), daemon=True).start()
        result = asyncio.run(cb.wait(timeout=5))
        assert result.code == "c1" and result.state == "s1"
    finally:
        cb.stop()


# ---------------------------------------------------------------------- probe
def test_probe_follows_hops_and_names_the_blocked_one():
    from tascreen.tv.mcp_client import probe_url

    server = FakeAuthServer(waf=True)
    server.start()
    try:
        ok = "\n".join(probe_url(f"{server.base}/authorize?redirect_uri=http://localhost:8765/callback&state=s"))
        assert "hop 0:" in ok and "-> 302" in ok and "redirects to the local callback" in ok

        blocked = "\n".join(probe_url(f"{server.base}/authorize?redirect_uri=http://127.0.0.1:8765/callback"))
        assert "-> 403 BLOCKED by CDN" in blocked
    finally:
        server.stop()



def test_cloudfront_error_page_is_a_block_whatever_the_status():
    """CloudFront also generates 400 pages; x-amz-cf-id alone is on every response."""
    from tascreen.tv.mcp_client import _cdn_verdict

    page = b"<html><title>ERROR: The request could not be satisfied</title>Generated by cloudfront</html>"
    assert _cdn_verdict(400, {"X-Cache": "Error from cloudfront"}, page)[0] is True
    assert _cdn_verdict(403, {"x-amz-cf-id": "x"}, page)[0] is True
    origin = b'{"error": "invalid_client"}'
    assert _cdn_verdict(400, {"x-amz-cf-id": "x", "X-Cache": "Miss from cloudfront"}, origin)[0] is False


# ------------------------------------------------------------- token expiry
def _sign_in(server, tmp_path):
    _client(server, tmp_path, interactive=True).list_tools()
    return FileTokenStorage(tmp_path / "tv_tokens.json")


def _expire(storage, server):
    """What an hour passing does: the server stops accepting the old access token."""
    data = json.loads(storage.path.read_text())
    data["tokens_saved_at"] = time.time() - 7200
    storage.path.write_text(json.dumps(data))
    server.valid_token = "only-a-refreshed-token-works-now"


def test_expired_token_is_refreshed_not_sent_to_a_browser(auth_server, tmp_path):
    storage = _sign_in(auth_server, tmp_path)
    assert storage.status()["expired"] is False and storage.status()["refresh_token"]
    _expire(storage, auth_server)
    assert storage.status()["expired"] is True

    headless = _client(auth_server, tmp_path, interactive=False)
    assert "get_quote" in describe_tools(headless.list_tools())
    assert auth_server.token_requests[-1]["grant_type"] == "refresh_token"
    assert storage.status()["expired"] is False            # new expiry recorded


def test_token_file_from_before_expiry_tracking_uses_its_age(auth_server, tmp_path):
    storage = _sign_in(auth_server, tmp_path)
    data = json.loads(storage.path.read_text())
    del data["tokens_saved_at"]
    storage.path.write_text(json.dumps(data))
    old = time.time() - 7200
    os.utime(storage.path, (old, old))
    auth_server.valid_token = "only-a-refreshed-token-works-now"

    _client(auth_server, tmp_path, interactive=False).list_tools()
    assert auth_server.token_requests[-1]["grant_type"] == "refresh_token"


def test_refused_refresh_explains_why_a_sign_in_is_needed(auth_server, tmp_path):
    storage = _sign_in(auth_server, tmp_path)
    _expire(storage, auth_server)
    auth_server.refresh_ok = False
    with pytest.raises(AuthorizationRequired, match="expired at .* refreshing it failed"):
        _client(auth_server, tmp_path, interactive=False).list_tools()


def test_token_status_never_contains_secrets(auth_server, tmp_path):
    status = json.dumps(_sign_in(auth_server, tmp_path).status())
    assert "access-token" not in status and "refresh-1" not in status


def test_refresh_behind_bot_protection_finds_the_real_token_endpoint(tmp_path):
    server = FakeAuthServer(waf=True)
    server.start()
    try:
        storage = _sign_in(server, tmp_path)
        _expire(storage, server)
        _client(server, tmp_path, interactive=False).list_tools()
        assert server.token_requests[-1]["grant_type"] == "refresh_token"
        blocked = [path for path, agent in server.user_agents
                   if path != "/authorize" and not agent.startswith("ta-screener")]
        assert blocked == []
        assert not any(path == "/token" for path, _ in server.user_agents)   # no guessed endpoint
    finally:
        server.stop()


# ------------------------------------------------------- one session, many calls
def _mcp_requests(server) -> int:
    return sum(1 for path, _ in server.user_agents if path.startswith("/mcp"))


def test_session_makes_many_calls_over_one_connection(auth_server, tmp_path):
    """Scanning thousands of symbols must not pay a handshake per call."""
    _sign_in(auth_server, tmp_path)
    client = _client(auth_server, tmp_path, interactive=False)
    symbols = ("NASDAQ:AAA", "NASDAQ:BBB", "NASDAQ:CCC")

    before = _mcp_requests(auth_server)
    for symbol in symbols:
        client.call_tool("get_quote", {"symbol": symbol})
    per_call = _mcp_requests(auth_server) - before

    async def three(session):
        return [await session.call_tool("get_quote", {"symbol": s}) for s in symbols]

    before = _mcp_requests(auth_server)
    results = client.with_session(three)
    in_session = _mcp_requests(auth_server) - before

    assert [json.loads(r.content[0].text)["symbol"] for r in results] == list(symbols)
    assert in_session < per_call
    assert len(auth_server.token_requests) == 1          # still no second sign-in


def test_token_expiring_in_the_middle_of_a_session_is_refreshed_at_the_real_endpoint(tmp_path):
    """The first live universe run: the token was valid when the session opened (so
    nothing was discovered), expired mid-run, and the SDK refreshed at its guessed
    <MCP host>/token -> 404 -> 'sign in again'. The token here lives 62 s; with the
    60 s safety margin it counts as expired about 2 s into the session."""
    server = FakeAuthServer(waf=True, expires_in=62)
    server.start()
    try:
        _sign_in(server, tmp_path)
        client = _client(server, tmp_path, interactive=False)

        async def slow(session):
            first = await session.call_tool("get_quote", {"symbol": "NASDAQ:AAA"})
            await asyncio.sleep(3)
            second = await session.call_tool("get_quote", {"symbol": "NASDAQ:BBB"})
            return first, second

        first, second = client.with_session(slow)
        assert not first.is_error and not second.is_error
        grants = [r["grant_type"] for r in server.token_requests]
        assert grants[0] == "authorization_code" and "refresh_token" in grants[1:]
        assert not any(path == "/token" for path, _ in server.user_agents)   # never guessed
    finally:
        server.stop()


def test_session_refuses_write_tools():
    client = TradingViewMCP(server=_fake_tradingview_mcp())

    async def write(session):
        return await session.call_tool("mcp-watchlist-add-to-watchlist", {"symbols": ["X"]})

    with pytest.raises(ProviderError, match="refusing to call"):
        client.with_session(write)
